namespace Troubleshooter_2.Enumerations
{
    public enum Languages
    {
        Arabic,
        Bulgarian,
        Chinese,
        Dutch,
        English,
        French,
        German,
        Greek,
        Hungarian,
        Italian,
        Korean,
        Latvian,
        Lithuanian,
        Polish,
        Portuguese,
        Romanian,
        Russian,
        Spanish,
        Swedish,
        Thai,
        TraditionalChinese,
        Turkish,
        Vietnamese
    }
}